theme: jekyll-theme-minimal

title: GiellaLT

description: <a href="/AboutGiellaLT.html">GiellaLT</a> provides an infrastructure for rule-based language technology aimed at minority and indigenous languages, and streamlines building anything from keyboards to speech technology. Read more <a href="https://indigenous-langtech.uit.no">about Why</a>. See also <a href="/infra/GettingStarted.html"><b>How to get started</b><a/>, and our <a href="/Personvern.html">Privacy document</a>.

plugins:
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter_opts:
    disable: true

# GitHub Pages kompatibilitet
repository: giellalt/giellalt.github.io

# Exclude Slidev directories and problematic files from Jekyll processing
exclude:
  - "test-presentation-slidev/"
  - "*-slidev/"
  - "test-slidev.sh"
  - "package.json"
  - "package-lock.json"
  - "node_modules/"
  - "vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - ".git/"
  - ".github/"
  - ".gitignore"
  - ".sass-cache/"
  - ".jekyll-cache/"
  - ".bundle/"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"

# Keep raw Slidev files accessible
keep_files:
  - "*-slidev"
